package com.nkming.sysusage

object Res
{
	const val ANIMATION_FAST = 200L
	const val ANIMATION_MID = 400L
	const val ANIMATION_SLOW = 500L

	const val ACTION_UNPLUG = "${BuildConfig.APPLICATION_ID}.ACTION_UNPLUG"
	const val ACTION_CPU_STAT_AVAILABLE =
			"${BuildConfig.APPLICATION_ID}.ACTION_CPU_STAT_AVAILABLE"
	const val ACTION_MEM_STAT_AVAILABLE =
			"${BuildConfig.APPLICATION_ID}.ACTION_MEM_STAT_AVAILABLE"
	const val ACTION_NET_STAT_AVAILABLE =
			"${BuildConfig.APPLICATION_ID}.ACTION_NET_STAT_AVAILABLE"
	const val ACTION_DISK_STAT_AVAILABLE =
			"${BuildConfig.APPLICATION_ID}.ACTION_DISK_STAT_AVAILABLE"
	const val EXTRA_STAT = "${BuildConfig.APPLICATION_ID}.EXTRA_STAT"
}
